version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=collectors_db
      - DB_USER=dummy
      - DB_PASSWORD=123456
      - DISPLAY=${DISPLAY}
    volumes:
      - ./app:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      - db
    network_mode: "host"  # For GUI display access on the host system

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: dummy
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: collectors_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
